### ISSUE TITLE
Create public postman collection for interacting with local backend stack

### ISSUE THREAD

**Issue by voutasaurus** [kiva/protocol-demo#43]
Postman is a convenient interactive way to document our API. We currently do not have a public postman collection for the backend API of the protocol stack. This issue is to create such a collection, including onboarding in guardian mode, in mobile mode, eKYC, and other administrative functions.

**Comment by jsaur** [comment]
Started a public collection here: https://dark-moon-2104.postman.co/workspace/Kiva-Protocol~84c4c589-9a6a-4dc7-a55e-39fdf93fd4e9/collection/14780387-f0e7151e-b76f-4dfb-92f5-e5609c105c83?ctx=documentation
Which results in these public docs: https://documenter.getpostman.com/view/14780387/Tzz4RzZc
(I plan on also adding some here for adding new controllers, schemas, etc)

**Comment by matt-raffel-kiva** [comment]
close due to project shutdown
