### ISSUE TITLE
dc-indy-pool image address already in use

### ISSUE THREAD

**Issue by natesulat** [kiva/protocol-demo#55]
In the demo setup, the `aries-guardianship-agency` docker-compose file begins running the Indy Pool on the same ports as the docker-compose file in the `protocol-demo` repo.

To wit:
https://github.com/kiva/aries-guardianship-agency/blob/main/docker-compose.yml#L27-L38
https://github.com/kiva/protocol-demo/blob/main/docker-compose.yml#L25-L36

This causes the following error when you try to run the demo.

<img width="1049" alt="Screen Shot 2021-09-10 at 9 34 24 AM" src="https://user-images.githubusercontent.com/8783200/132887272-bcc6e7d7-e97b-49a3-965c-f8d4126a9c8c.png">

**Comment by natesulat** [comment]
@jsaur Confirmed that the build succeeds. Yay!

Have another error when attempting to stop the build which MIGHT be related? Let me know if it's not and I'll close the issue.

<img width="1640" alt="Screen Shot 2021-09-10 at 10 18 33 AM" src="https://user-images.githubusercontent.com/8783200/132892541-7fedec65-a7be-46f9-89f2-8b23a30a77a7.png">

**Comment by jsaur** [comment]
Just to confirm, did you run the simple_start script and then the simple_stop script? Because if you ran full_start and then simple_stop there may be additional controllers attached to the agency-network. You can see what services are still running by doing: docker ps

**Comment by natesulat** [comment]
The sequence of events was (from the `protocol-all` directory)

```
13238  docker ps -aq | xargs docker rm -f
13239  docker network prune -f
13240  ./protocol-demo/scripts/simple_build.sh
13241  cd protocol-demo
13242  ./scripts/simple_start.sh
13243  npm run test
13244  ./scripts/simple_stop.sh
```
